Feature: Test Development
    Scenario: Variable Tests
        Given I store the value "Suren Rodrigo" in variable "MyName" as a "string"
        Then The value in variable "MyName" of type "string" equals to "Suren Rodrigo"
        And I store the value "10" in variable "numberTen" as a "number"
        Then The value in variable "numberTen" of type "number" equals to "10"
        And I store the value "10" in variable "numberTen1" as a "number"
        And I store the value "Suren Rodrigo" in variable "MyName1" as a "string"
        When The value in variable "numberTen" of type "number" equals to variable "numberTen1"
        When The value in variable "MyName" of type "string" equals to variable "MyName1"
        Given I store the value "20" in variable "numberTwenty" as a "number"
        And I Add variable "numberTwenty" to "numberTen" and store in "numberThirty"
        Then The value in variable "numberThirty" of type "number" equals to "30"
        When I Subtract variable "numberTwenty" from "numberTen" and store in "subtractValue"
        Then The value in variable "subtractValue" of type "number" equals to "10"
        When I Multiply variable "numberTwenty" from "numberTen" and store in "multiplyValue"
        Then The value in variable "multiplyValue" of type "number" equals to "200"
        When I Divide variable "numberTwenty" from "numberTen" and store in "divideValue"
        Then The value in variable "divideValue" of type "number" equals to "2"